"""Build the SUMO networks from source, rather than shipping hand-edited XML.

Two networks:

* ``junction4``  -- one four-arm signalised junction, 3 lanes per approach.
* ``corridor3``  -- three signalised junctions on an arterial, for the
                    downstream-effect experiments.

Everything is generated by ``netconvert`` from plain node/edge/connection files
so the geometry is reproducible and reviewable in a diff. Hand-editing a
``.net.xml`` is a one-way door: the file is machine-generated, enormous, and the
next person cannot tell which parts were intentional.

TRAFFIC SIDE
------------
SUMO defaults to right-hand traffic. India drives on the left, and the choice
changes which turn is the easy one and therefore how the junction discharges.
The networks here are built with ``--lefthand`` so turning movements match the
Indian context the project targets. This is set in exactly one place, and every
network inherits it -- mixing conventions between networks would silently
invalidate any comparison between them.

PHASING
-------
Four-phase, one approach at a time, with 3 s yellow and 2 s all-red between
phases. This costs capacity against an opposed-pairs plan, but it buys the
property the emergency case needs: while one arm is green no conflicting
movement exists anywhere in the junction box, so an ambulance released onto its
approach has a genuinely clear path rather than one that merely has priority.
"""

from __future__ import annotations

import argparse
import glob
import os
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
NETS = HERE / "nets"

ARM_LEN = 250.0          # m of each approach
LANES = 3
SPEED = 13.89            # m/s ~= 50 km/h urban arterial
YELLOW = 3
ALL_RED = 2

ARMS = [("N", 0.0, 1.0), ("E", 1.0, 0.0), ("S", 0.0, -1.0), ("W", -1.0, 0.0)]


# ---------------------------------------------------------------- toolchain

def sumo_tool(name: str) -> str:
    """Locate a SUMO binary, whether installed via pip or a system install."""
    home = os.environ.get("SUMO_HOME")
    candidates = []
    if home:
        candidates.append(os.path.join(home, "bin", name + ".exe"))
        candidates.append(os.path.join(home, "bin", name))
    try:
        import sumo  # noqa: F401 - provided by the eclipse-sumo wheel
        root = os.path.dirname(sumo.__file__)
        candidates += glob.glob(os.path.join(root, "**", name + ".exe"), recursive=True)
        candidates += glob.glob(os.path.join(root, "**", name), recursive=True)
    except ImportError:
        pass
    found = shutil.which(name)
    if found:
        candidates.append(found)
    for c in candidates:
        if c and os.path.isfile(c):
            return c
    raise FileNotFoundError(
        f"could not locate SUMO tool {name!r}. Install with `pip install eclipse-sumo` "
        f"or set SUMO_HOME."
    )


# ---------------------------------------------------------------- junction4

def write_junction4(out: Path) -> None:
    out.mkdir(parents=True, exist_ok=True)

    nodes = ['<nodes>', f'  <node id="C" x="0" y="0" type="traffic_light" tlType="static"/>']
    for name, dx, dy in ARMS:
        nodes.append(f'  <node id="{name}" x="{dx * ARM_LEN:.1f}" y="{dy * ARM_LEN:.1f}" type="priority"/>')
    nodes.append('</nodes>')
    (out / "nodes.nod.xml").write_text("\n".join(nodes), encoding="utf-8")

    edges = ['<edges>']
    for name, _, _ in ARMS:
        # inbound (approach) and outbound (exit) for every arm
        edges.append(
            f'  <edge id="{name}2C" from="{name}" to="C" priority="2" '
            f'numLanes="{LANES}" speed="{SPEED}"/>'
        )
        edges.append(
            f'  <edge id="C2{name}" from="C" to="{name}" priority="2" '
            f'numLanes="{LANES}" speed="{SPEED}"/>'
        )
    edges.append('</edges>')
    (out / "edges.edg.xml").write_text("\n".join(edges), encoding="utf-8")

    # Four-phase plan, one arm at a time. Phase strings are written by
    # netconvert from the connection topology; we only fix the durations here
    # and let netconvert generate the state strings, because hand-writing them
    # against an unknown link ordering is how phase bugs are introduced.
    (out / "tls.add.xml").write_text(
        '<additional>\n'
        '  <!-- durations only; netconvert generates the state strings -->\n'
        '</additional>\n', encoding="utf-8"
    )

    netconvert = sumo_tool("netconvert")
    cmd = [
        netconvert,
        "--node-files", str(out / "nodes.nod.xml"),
        "--edge-files", str(out / "edges.edg.xml"),
        "--output-file", str(out / "net.net.xml"),
        "--tls.guess", "true",
        "--tls.default-type", "static",
        "--tls.yellow.time", str(YELLOW),
        "--tls.allred.time", str(ALL_RED),
        "--tls.green.time", "25",
        # one arm at a time: netconvert's "incoming" layout gives each approach
        # its own phase instead of pairing opposing movements
        "--tls.layout", "incoming",
        "--lefthand", "true",
        "--no-turnarounds", "true",
        "--default.junctions.keep-clear", "true",
        "--no-warnings", "true",
    ]
    run(cmd, "junction4 netconvert")


# ---------------------------------------------------------------- corridor3

def write_corridor3(out: Path, spacings=(600.0, 550.0, 700.0)) -> None:
    """Three signalised junctions in a line, with a cross street at each."""
    out.mkdir(parents=True, exist_ok=True)
    xs = [0.0]
    for s in spacings[:2]:
        xs.append(xs[-1] + s)
    approach = 400.0
    cross = 250.0

    nodes = ['<nodes>']
    nodes.append(f'  <node id="W0" x="{xs[0] - approach:.1f}" y="0" type="priority"/>')
    for i, x in enumerate(xs, start=1):
        nodes.append(f'  <node id="J{i}" x="{x:.1f}" y="0" type="traffic_light" tlType="static"/>')
        nodes.append(f'  <node id="N{i}" x="{x:.1f}" y="{cross:.1f}" type="priority"/>')
        nodes.append(f'  <node id="S{i}" x="{x:.1f}" y="{-cross:.1f}" type="priority"/>')
    nodes.append(f'  <node id="E0" x="{xs[-1] + spacings[2]:.1f}" y="0" type="priority"/>')
    nodes.append('</nodes>')
    (out / "nodes.nod.xml").write_text("\n".join(nodes), encoding="utf-8")

    def pair(a: str, b: str) -> list[str]:
        return [
            f'  <edge id="{a}2{b}" from="{a}" to="{b}" priority="3" numLanes="{LANES}" speed="{SPEED}"/>',
            f'  <edge id="{b}2{a}" from="{b}" to="{a}" priority="3" numLanes="{LANES}" speed="{SPEED}"/>',
        ]

    edges = ['<edges>']
    chain = ["W0"] + [f"J{i}" for i in range(1, len(xs) + 1)] + ["E0"]
    for a, b in zip(chain, chain[1:]):
        edges += pair(a, b)
    for i in range(1, len(xs) + 1):
        edges += pair(f"N{i}", f"J{i}")
        edges += pair(f"S{i}", f"J{i}")
    edges.append('</edges>')
    (out / "edges.edg.xml").write_text("\n".join(edges), encoding="utf-8")

    cmd = [
        sumo_tool("netconvert"),
        "--node-files", str(out / "nodes.nod.xml"),
        "--edge-files", str(out / "edges.edg.xml"),
        "--output-file", str(out / "net.net.xml"),
        "--tls.guess", "true",
        "--tls.default-type", "static",
        "--tls.yellow.time", str(YELLOW),
        "--tls.allred.time", str(ALL_RED),
        "--tls.green.time", "25",
        "--tls.layout", "incoming",
        "--lefthand", "true",
        "--no-turnarounds", "true",
        "--default.junctions.keep-clear", "true",
        "--no-warnings", "true",
    ]
    run(cmd, "corridor3 netconvert")


# ---------------------------------------------------------------- helpers

def run(cmd: list[str], label: str) -> None:
    res = subprocess.run(cmd, capture_output=True, text=True)
    if res.returncode != 0:
        print(f"[{label}] FAILED", file=sys.stderr)
        print(res.stdout, file=sys.stderr)
        print(res.stderr, file=sys.stderr)
        raise SystemExit(res.returncode)
    print(f"[{label}] ok")


def summarise(net: Path) -> None:
    """Print what was actually built, so a broken network is visible immediately."""
    import sumolib
    n = sumolib.net.readNet(str(net))
    tls = n.getTrafficLights()
    print(f"  {net.name}: {len(n.getNodes())} nodes, {len(n.getEdges())} edges, "
          f"{len(tls)} traffic light(s)")
    for t in tls:
        programs = t.getPrograms()
        for pid, prog in programs.items():
            phases = prog.getPhases()
            greens = [p for p in phases if "G" in p.state or "g" in p.state]
            print(f"    tls {t.getID()} program {pid}: {len(phases)} phases "
                  f"({len(greens)} with green), cycle "
                  f"{sum(p.duration for p in phases):.0f} s")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--only", choices=["junction4", "corridor3"], default=None)
    args = ap.parse_args()

    if args.only in (None, "junction4"):
        write_junction4(NETS / "junction4")
        summarise(NETS / "junction4" / "net.net.xml")
    if args.only in (None, "corridor3"):
        write_corridor3(NETS / "corridor3")
        summarise(NETS / "corridor3" / "net.net.xml")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
